import sqlite3
import os
import json
from datetime import datetime

class StateManager:
    def __init__(self, db_path: str = None):
        if db_path is None:
            # Default to a hidden directory in the user's home for persistence
            home_dir = os.path.expanduser("~")
            app_dir = os.path.join(home_dir, ".aicofounder")
            os.makedirs(app_dir, exist_ok=True)
            self.db_path = os.path.join(app_dir, "projects.db")
            self.reports_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reports")
            os.makedirs(self.reports_dir, exist_ok=True)
        else:
            self.db_path = db_path
        self._initialize_db()

    def _initialize_db(self):
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS projects (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL UNIQUE,
                    data TEXT
                )
            """)
            conn.commit()

    def save_project(self, project_name: str, project_data: dict):
        """Saves or updates project data."""
        data_json = json.dumps(project_data)
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(
                "INSERT OR REPLACE INTO projects (name, data) VALUES (?, ?)",
                (project_name, data_json)
            )
            conn.commit()

    def load_project(self, project_name: str) -> dict | None:
        """Loads project data by name."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT data FROM projects WHERE name = ?", (project_name,))
            result = cursor.fetchone()
            if result:
                return json.loads(result[0])
            return None

    def list_projects(self) -> list[str]:
        """Lists all saved project names."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT name FROM projects")
            return [row[0] for row in cursor.fetchall()]

    def delete_project(self, project_name: str):
        """Deletes a project by name."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("DELETE FROM projects WHERE name = ?", (project_name,))
            conn.commit()

    def export_report(self, project_name: str) -> str:
        """Generates a Markdown report for the project."""
        data = self.load_project(project_name)
        if not data:
            return "Project not found."
        
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"Report_{project_name}_{timestamp}.md"
        filepath = os.path.join(self.reports_dir, filename)
        
        report_content = f"""# AICoFounder Startup Report: {project_name}
Generated on: {datetime.now().strftime("%B %d, %Y")}

## 1. Vision & Canvas
**Idea:** {data.get('idea', 'N/A')}
**Target Audience:** {data.get('audience', 'N/A')}
**Problem Statement:** {data.get('problem', 'N/A')}

## 2. Market Research
{data.get('research_data', 'No research data collected.')}

## 3. Validation Analysis
{data.get('validation_report', 'No validation report generated.')}

## 4. MVP Roadmap
{data.get('mvp_roadmap', 'No roadmap generated.')}

## 5. Technical Audit
{data.get('codebase_audit', 'No codebase audit performed.')}

---
Generated by AICoFounder CLI (Groq-Powered)
"""
        with open(filepath, "w") as f:
            f.write(report_content)
        
        return filepath

if __name__ == "__main__":
    # Example usage (for testing purposes)
    state_manager = StateManager(db_path="test_projects.db")
    state_manager.save_project("TestStartup", {"idea": "Test", "phase": "Build"})
    print(f"Report exported to: {state_manager.export_report('TestStartup')}")
    os.remove("test_projects.db")
